#pragma once

//// HTTP METHODS ////
#define HTTP_CONTINUE "HTTP/1.1 100 Continue\n"
#define HTTP_SWITCHING_PROTOCOLS "HTTP/1.1 101 Switching Protocols\n"
#define HTTP_OK "HTTP/1.1 200 OK\n"
#define HTTP_CREATED "HTTP/1.1 201 Created\n"
#define HTTP_ACCEPTED "HTTP/1.1 202 Accepted\n"
#define HTTP_NON_AUTHORITATIVE_INFORMATION "HTTP/1.1 203 Non-Authoritative Information\n"
#define HTTP_NO_CONTENT "HTTP/1.1 204 No Content\n"
#define HTTP_RESET_CONTENT "HTTP/1.1 205 Reset Content\n"
#define HTTP_PARTIAL_CONTENT "HTTP/1.1 206 Partial Content\n"
#define HTTP_MULTIPLE_CHOICES "HTTP/1.1 300 Multiple Choices\n"
#define HTTP_MOVED_PERMANENTLY "HTTP/1.1 301 Moved Permanently\n"
#define HTTP_FOUND "HTTP/1.1 302 Found\n"
#define HTTP_SEE_OTHER "HTTP/1.1 303 See Other\n"
#define HTTP_NOT_MODIFIED "HTTP/1.1 304 Not Modified\n"
#define HTTP_USE_PROXY "HTTP/1.1 305 Use Proxy\n"
#define HTTP_TEMPORARY_REDIRECT "HTTP/1.1 307 Temporary Redirect\n"
#define HTTP_BAD_REQUEST "HTTP/1.1 400 Bad Request\n"
#define HTTP_UNAUTHORIZED "HTTP/1.1 401 Unauthorized\n"
#define HTTP_PAYMENT_REQUIRED "HTTP/1.1 402 Payment Required\n"
#define HTTP_FORBIDDEN "HTTP/1.1 403 Forbidden\n"
#define HTTP_NOT_FOUND "HTTP/1.1 404 Not Found\n"
#define HTTP_METHOD_NOT_ALLOWED "HTTP/1.1 405 Method Not Allowed\n"
#define HTTP_NOT_ACCEPTABLE "HTTP/1.1 406 Not Acceptable\n"
#define HTTP_PROXY_AUTHENTICATION_REQUIRED "HTTP/1.1 407 Proxy Authentication Required\n"
#define HTTP_REQUEST_TIMEOUT "HTTP/1.1 408 Request Timeout\n"
#define HTTP_CONFLICT "HTTP/1.1 409 Conflict\n"
#define HTTP_GONE "HTTP/1.1 410 Gone\n"
#define HTTP_LENGTH_REQUIRED "HTTP/1.1 411 Length Required\n"
#define HTTP_PRECONDITION_FAILED "HTTP/1.1 412 Precondition Failed\n"
#define HTTP_PAYLOAD_TOO_LARGE "HTTP/1.1 413 Payload Too Large\n"
#define HTTP_URI_TOO_LONG "HTTP/1.1 414 URI Too Long\n"
#define HTTP_UNSUPPORTED_MEDIA_TYPE "HTTP/1.1 415 Unsupported Media Type\n"
#define HTTP_RANGE_NOT_SATISFIABLE "HTTP/1.1 416 Range Not Satisfiable\n"
#define HTTP_EXPECTATION_FAILED "HTTP/1.1 417 Expectation Failed\n"
#define HTTP_IM_A_TEAPOT "HTTP/1.1 418 I'm a teapot\n"
#define HTTP_MISDIRECTED_REQUEST "HTTP/1.1 421 Misdirected Request\n"
#define HTTP_UNPROCESSABLE_ENTITY "HTTP/1.1 422 Unprocessable Entity\n"
#define HTTP_LOCKED "HTTP/1.1 423 Locked\n"
#define HTTP_FAILED_DEPENDENCY "HTTP/1.1 424 Failed Dependency\n"
#define HTTP_TOO_EARLY "HTTP/1.1 425 Too Early\n"
#define HTTP_UPGRADE_REQUIRED "HTTP/1.1 426 Upgrade Required\n"
#define HTTP_PRECONDITION_REQUIRED "HTTP/1.1 428 Precondition Required\n"
#define HTTP_TOO_MANY_REQUESTS "HTTP/1.1 429 Too Many Requests\n"
#define HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE "HTTP/1.1 431 Request Header Fields Too Large\n"
#define HTTP_UNAVAILABLE_FOR_LEGAL_REASONS "HTTP/1.1 451 Unavailable For Legal Reasons\n"
#define HTTP_INTERNAL_SERVER_ERROR "HTTP/1.1 500 Internal Server Error\n"
#define HTTP_NOT_IMPLEMENTED "HTTP/1.1 501 Not Implemented\n"
#define HTTP_BAD_GATEWAY "HTTP/1.1 502 Bad Gateway\n"
#define HTTP_SERVICE_UNAVAILABLE "HTTP/1.1 503 Service Unavailable\n"
#define HTTP_GATEWAY_TIMEOUT "HTTP/1.1 504 Gateway Timeout\n"
#define HTTP_HTTP_VERSION_NOT_SUPPORTED "HTTP/1.1 505 HTTP Version Not Supported\n"
#define HTTP_VARIANT_ALSO_NEGOTIATES "HTTP/1.1 506 Variant Also Negotiates\n"
#define HTTP_INSUFFICIENT_STORAGE "HTTP/1.1 507 Insufficient Storage\n"
#define HTTP_LOOP_DETECTED "HTTP/1.1 508 Loop Detected\n"
#define HTTP_NOT_EXTENDED "HTTP/1.1 510 Not Extended\n"
#define HTTP_NETWORK_AUTHENTICATION_REQUIRED "HTTP/1.1 511 Network Authentication Required\n"
//// END HTTP METHODS ////

//// RETURN CONTENT TYPES ////
#define CONTENT_TYPE_PLAIN "Content-Type: text/plain\n"
#define CONTENT_TYPE_HTML "Content-Type: text/html\n"
//// END RETURN CONTENT TYPES ////
